name: Upload Python Package (CPU Version)

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and publish (e.g. v1.2.3)'
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.event.release.tag_name }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: |
        # Create a temporary directory for CPU version
        mkdir -p temp-cpu
        cp -r subwiz temp-cpu/
        cp requirements-cpu.txt temp-cpu/requirements.txt
        cp pyproject-cpu.toml temp-cpu/pyproject.toml
        cd temp-cpu
        python -m build
        cd ..
        mv temp-cpu/dist/* dist/
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_CPU }}
        repository_url: https://upload.pypi.org/legacy/
        packages_dir: dist/ 